### ISSUE TITLE
no .exe

### ISSUE THREAD

**Issue by BenGuse219** [aeon0/botty#101]
Hello. I am very new to GitHub but I can't find the .exe?

I downloaded the very first one you released and it came with a .exe but now I cant find it.

**Comment by karibuTW** [comment]
Hi, you have 2 ways to run this project

Option 1: Use the stable release:
https://github.com/aeon0/botty/releases/tag/v0.3.0
This includes the .exe
And it's the easiest to use.

Option 2: Use the latest release: (What you have done I think)
https://github.com/aeon0/botty/archive/refs/heads/master.zip
But you need to:
1) Install miniconda (https://docs.conda.io/en/latest/miniconda.html). Note: You will have to check "Add conda to my PATH environment variable" in order to access the conda command in the cmd.
2) open cmd and do:
> cd botty (Where you downloaded it)
> conda env create environment.yml
> conda activate botty
> python src/run.py

**Comment by BenGuse219** [comment]
Thanks! That's exactly what I did the first time I forgot I downloaded win7 to unzip the rar! 

i have 1 more question. but i think im suppose to make a new "issue" right?

is there any way to get the bot to buy potions at the start of the game?

**Comment by aeon0** [comment]
Issues are only for bugs, thus the template to fill out all needed questions. Please ask your questions in the discord server. Closing this.
