### ISSUE TITLE
Problem with shenk

### ISSUE THREAD

**Issue by MrMefetran** [aeon0/botty#89]
**Botty Version**
0.3.0

**Describe the bug**
bot don't do shenk

**To Reproduce**
Go on shenk after eldritch

**Expected behavior**
bot don't do shenk because he needs 1 or 2 more TPs to reach it

**Screenshots / Video**
short video https://disk.yandex.ru/i/3iqMWL0J0kTyyw
2 full runs https://disk.yandex.ru/i/0ETBROFilXfGYA

**Logs**
[2021-11-23 12:46:19,442] INFO       Run Shenk
[2021-11-23 12:46:36,790] ERROR      Got stuck exit pather
[2021-11-23 12:46:42,108] INFO       End game. Elapsed time: 104.17s

**Additional info**
Add any other information about the problem here.

**Comment by aeon0** [comment]
I would say this is partly a known issue, partly fixed on current master, partly an issue with your graphics.
#### 1) Known issue
Because Shenk has many mobs on the way, static pathing will often fail because of teleport cancel when hit. That is why there needs to be template pathing such as it is down in town. This has other drawbacks. E.g. when a template is obstructed by enemies it might not be found
#### 2) Partly fixed
#73 Here another shenk template is added to overcome the issue of getting stuck at end of stairs
#### 3) Partly your graphics
Even when there are no enemies and all the templates are clearly visible it looks like botty does not detect the templates (you can see which ones in assets/templates/shenk). In the latest master there is more debug data available in the graphic debugger mode. I'd suggest running it while in a5 town and see if you get the same scores as in the screenshot on the readme. 

Closing as it is not a clear bug per-se and mostly fixed. It will never have 100% success rate.
